config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	root 'pages#dashboard', :as => :home

	get "my_articles", to: "articles#display_all_articles", :as => :display_blog 
	#get "post/:id", to: "articles#display_selected_article", :as => :display_selected_article
	get "manage_stallions", to: "stallions#all_stallions", :as => :all_stallions
	get "stallions_for_sale",  to: "stallions#stallions_for_sale", :as => :all_stallions_for_sale

	get "manage_show_team", to: "members#display_members", :as => :display_members

	resources :articles
	resources :stallions
	resources :members
	resources :emails
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	mount_uploader :image, ImageUploader
	
	validates :title, presence: true, length: {minimum: 5}
end

app/models/member.rb
class Member < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/stallion.rb
class Stallion < ApplicationRecord

	mount_uploader :image, ImageUploader
	mount_uploader :mother_image, ImageUploader
	mount_uploader :father_image, ImageUploader

	validates :name, presence: true, length: {maximum: 35}
	validates :image, presence: true
	validates :reg_number, presence: true
	validates :birth_date, presence: true
	validates :sex, presence: true
	validates :colour, presence: true
	validates :markings, presence: true
	validates :breeder, presence: true
	validates :description, presence: true
	validates :mother_name, presence: true
	validates :mother_image, presence: true
	validates :father_name, presence: true
	validates :father_image, presence: true
	validates :breeding_description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  private
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path, notice: "Please Login to view that page!"
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_post, only: [:show, :update, :destroy]

	def index
		@articles = Article.all
		render json: @articles
	end

	def display_all_articles
		@articles = Article.all
	end

	def display_selected_article
		@article = Article.find(params[:id])
	end

	def show
		@article = Article.find(params[:id])
		render json: @article
	end

	def edit
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		
		if(@article.save)
			redirect_to display_blog_path
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])

		if(@article.update(article_params))
			redirect_to display_blog_path
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to display_blog_path
	end

	private
		def set_post
			@article = Article.find(params[:id])
		end

		def article_params
			params.require(:article).permit(:title, :body, :image)
		end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	before_action :set_post, only: [:show]

	def index
		@members = Member.all
		render json: @members
	end

	def display_members
		@members = Member.all
	end

	def show
		render json: @member
	end

	def new
		@member = Member.new
	end

	def create
		@member = Member.new(member_params)

		if(@member.save)
			flash[:notice] = "Member Created"
			redirect_to display_members_path
		else
			render 'new'
		end
	end

	def edit
		@member = Member.find(params[:id])
	end

	def update
		@member = Member.find(params[:id])

		if(@member.update(member_params))
			redirect_to display_members_path
		else
			render 'edit'
		end
	end

	def destroy
		@member = Member.find(params[:id])
		@member.destroy
		redirect_to display_members_path
	end

	private

		def set_post
			@member = Member.find(params[:id])
		end
		
		def member_params
			params.require(:member).permit(:name, :age, :image, :description, :remove_image)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!
	def dashboard

	end
end

app/controllers/stallions_controller.rb
class StallionsController < ApplicationController
	before_action :set_post, only: [:show, :update, :destroy]

	def index
		@stallions = Stallion.all

		#@stallions.image.thumb.url 
		render json: @stallions
	end

	def show
		render json: @stallion
	end

	def new
		@stallion = Stallion.new
	end

	def all_stallions
		@stallions = Stallion.all
	end

	def stallions_for_sale
		@stallions = Stallion.where(:for_sale => true)
		render json: @stallions
	end

	def edit
		@stallion = Stallion.find(params[:id])
	end

	def update
		@stallion = Stallion.find(params[:id])

		if(@stallion.update(stallion_params))
			redirect_to all_stallions_path
		else
			render 'edit'
		end
	end

	def create
		@stallion = Stallion.new(stallion_params)

		if(@stallion.save)
			flash[:notice] = "Stallion Created"
			redirect_to all_stallions_path
		else
			render 'new'
		end
	end

	def destroy
		@stallion = Stallion.find(params[:id])
		@stallion.destroy
		redirect_to all_stallions_path
	end

	private

		def set_post
			@stallion = Stallion.find(params[:id])
		end
		
		def stallion_params
			params.require(:stallion).permit(:name, :for_sale, :price, :image, :reg_number, :birth_date, :sex, 
				:colour, :markings, :breeder, :description, :mother_name, :mother_image, :father_name,
				:father_image, :breeding_description, :remove_image)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stallions_helper.rb
module StallionsHelper
end

app/views/articles/display_all_articles.html.erb
<div class="content">
	<ol class="breadcrumb">
		<li class="breadcrumb-item active">Blog Management</li>
	</ol>
	<%= link_to "Create Post", new_article_path, class: 'btn btn-primary float-right' %>
	<div class="container">
		
			<div class="row">
				<% @articles.each do |article| %>
					<div class="col-sm-6 col-lg-4">
						<div class="card">
							<div class="card-image"><%= image_tag article.image_url(), class: 'card-image' %></div>
							<div class="card-block">
								<h4 class="card-title"><%= article.title %></h4>
								<p class="published-date">Published <%= article.created_at.strftime("%b %d, %Y") %></p>
								<p class="card-text"><%= truncate(article.body, length: 150) %></p>
								<%= link_to 'Edit', edit_article_path(article), class: 'btn btn-primary' %>
								<%= link_to 'Delete', article_path(article), 
										method: :delete, data: {confirm: 'Are you sure?'}, 
										class: 'btn btn-primary' %>
							</div>
						</div>
					</div>
				<% end %>
			</div>
	</div>
</div>

app/views/articles/display_selected_article.html.erb
<div class="content">
	<h3><%= @article.title %></h3>
	<p><%= @article.body %></p>

	<%= link_to edit_article_path do %>
		<button type="button" class="button-edit btn btn-default">Edit</button>
	<% end %>
	<%= button_to "Delete", article_path(@article), 
			method: :delete,
			data: {confirm: 'Are you sure?'},
			:class => 'btn btn-default button-delete' %>
</div>

app/views/articles/edit.html.erb
<div class="content">
	<ol class="breadcrumb">
		<li class="breadcrumb-item active">Blog Management / Edit Post</li>
	</ol>
	<div class="container">
		<%= form_for @article, :html => {:multipart => true} do |f| %>

		<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class:'form-control', placeholder:'Title' %>
			</div>

			<div class="form-group">
				<%= f.label :image %>
				<div class="img-container">
					<%= image_tag @article.image.url, id:"img_prev1", class:"img-thumbnail hidden" %>
				</div>
				<%= f.file_field :image, id: "main-upload", :class => "btn btn-default", onchange:"preview_image(event, 'img_prev1')"%>
			</div>
			
			<div class="form-group">
				<%= f.label :body %>
				<%= f.text_area :body, class:'form-control', rows:'12' %>
			</div>

			<%= f.submit "Submit", class:'btn btn-primary'%>

		<% end %>
	</div>
</div>

app/views/articles/new.html.erb
<div class="content">
	<ol class="breadcrumb">
		<li class="breadcrumb-item active">Blog Management / New Post</li>
	</ol>

	<div class="container">
		<%= form_for @article, :html => {:multipart => true} do |f| %>
			
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class:'form-control', placeholder:'Title' %>
			</div>

			<div class="form-group">
					<%= f.label :image %>
					<div class="img-container">
						<img id="img_prev1" src="#" alt="" class="img-thumbnail hidden"/>
					</div>
					<%= f.file_field :image, id: "main-upload", :class => "btn btn-default", onchange:"preview_image(event, 'img_prev1')"%>
			</div>
			
			<div class="form-group">
				<%= f.label :body %>
				<%= f.text_area :body, class:'form-control', rows:'12' %>
			</div>

			<%= f.submit "Create Post", class:'btn btn-primary'%>

		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminServer</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <% if user_signed_in? %>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" style="color: #aaaaaa">My CMS</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Options</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" routerLink="dashboard">Dashboard</a>
                            <a class="dropdown-item" href="#">Go To Site</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav navbar-right">
                    <span class="navbar-text" style="margin-right: 15px">Welcome Shirley</span>
                        <%= button_to "Logout", destroy_user_session_path, 
                            method: :delete,
                            :class => 'btn btn-primary' %>
                </ul> 
            </div>
        </nav>

        <div class="management-tab">
            <div class="list-group">
                <button type="button" class="list-group-item list-group-item-action active">
                Website Management
                </button>
                <button type="button" class="list-group-item list-group-item-action">Manage Homepage</button>
                <%= button_to "Manage Stallions Page", all_stallions_path, method: :get, :class => "list-group-item list-group-item-action" %>
                <%= button_to "Manage Show Team Page", display_members_path, method: :get, :class => "list-group-item list-group-item-action" %>
                <button type="button" class="list-group-item list-group-item-action">Manage For Sale Page</button>
                <%= button_to "Manage Blog", display_blog_path, method: :get, :class => "list-group-item list-group-item-action" %>
                <button type="button" class="list-group-item list-group-item-action">Contact Info</button>
            </div>
        </div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/members/display_members.html.erb
<div class="content">
	<ol class="breadcrumb">
		<li class="breadcrumb-item active">Show Team Management</li>
	</ol>
	<table>
		<tr>
			<th>Name</th>
			<th>Age</th>
			<th>Image</th>
			<th>Options</th>
		</tr>
		<% @members.each do |member| %>
		<tr>
			<td><%= member.name %></td>
			<td><%= member.age %></td>
			<td><%= image_tag member.image.url %></td>
			<td>
				<%= button_to "Edit", edit_member_path(member), 
							method: :get,
							:class => 'btn btn-default button-delete' %>
				<%= button_to "Delete", member_path(member), 
							method: :delete,
							data: {confirm: 'Are you sure?'},
							:class => 'btn btn-default button-delete' %>
			</td>
		</tr>
		<% end %>
	</table>
	<%= link_to "Add Show Team Member", new_member_path %>
</div>

app/views/members/edit.html.erb
<div class="content">
	<ol class="breadcrumb">
		<li class="breadcrumb-item active">Show Team Management / Edit Member</li>
	</ol>
	<div class="container">
		<%= form_for @member, :html => {:multipart => true} do |f| %>

			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class:'form-control col-md-3'%>
			</div>

			<div class="form-group">
				<%= f.label :age %>
				<%= f.number_field  :age, class:'form-control col-md-3' %>
			</div>

			<div class="form-group">
				<%= f.label :image %>
				<div class="img-container">
					<%= image_tag @member.image.url, id:"img_prev1", class:"img-thumbnail hidden" %>
				</div>
				<%= f.file_field :image, id: "main-upload", :class => "btn btn-default", onchange:"preview_image(event, 'img_prev1')"%>
			</div>

			<div class="form-group">
				<%= f.label :description %>
				<%= f.text_area :description, class:'form-control', rows: '7'%>
			</div>

			<%= f.submit "Submit", class:'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/members/new.html.erb
<div class="content">
	<ol class="breadcrumb">
		<li class="breadcrumb-item active">Show Team Management / Add Member</li>
	</ol>
	<div class="container">
		<%= form_for @member, :html => {:multipart => true} do |f| %>

			<% if @member.errors.any? %>
				<% @member.errors.full_messages.each do |msg| %>
					<div class="alert alert-danger"><%= msg %></div>
				<% end %>
			<% end %>

			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class:'form-control col-md-3', placeholder:'Name'%>
			</div>


			<div class="form-group">
				<%= f.label :age %>
				<%= f.number_field  :age, class:'form-control col-md-3', placeholder:'Age' %>
			</div>


			<div class="form-group">
				<%= f.label :image %>
				<div class="img-container">
					<img id="img_prev1" src="#" alt="" class="img-thumbnail hidden"/>
				</div>
				<%= f.file_field :image, id: "main-upload", :class => "btn btn-default", onchange:"preview_image(event, 'img_prev1')"%>
			</div>

			<div class="form-group">
				<%= f.label :description %>
				<%= f.text_area :description, class:'form-control', rows:'7', placeholder:'Enter a description here ...'%>
			</div>

			<%= f.submit "Submit", class:'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/pages/dashboard.html.erb
<div class="content">
	<h1>Dashboard</h1>
</div>

app/views/stallions/all_stallions.html.erb
<div class="content">
	<ol class="breadcrumb">
		<li class="breadcrumb-item active">Stallions Management</li>
	</ol>
	<%= link_to "Add Stallion", new_stallion_path, class:"btn btn-primary float-right" %>
	<div class="container">
		<table>
			<tr>
				<th><h4>Name</h4></th>
				<th><h4>Image</h4></th>
				<th><h4>Options</h4></th>
			</tr>
			<% @stallions.each do |stallion| %>
			<tr>
				<td><p><%= stallion.name %></p></td>
				<td><%= image_tag stallion.image.url, :class => "stallion-thumb"%></td>
				<td>
					<%= button_to "Edit", edit_stallion_path(stallion), 
								method: :get,
								:class => 'btn btn-primary button-delete' %>
					<%= button_to "Delete", stallion_path(stallion), 
								method: :delete,
								data: {confirm: 'Are you sure?'},
								:class => 'btn btn-primary button-delete' %>
				</td>
			</tr>
			<% end %>
		</table>
		
	</div>
</div>

app/views/stallions/edit.html.erb
<div class="content">
	<ol class="breadcrumb">
		<li class="breadcrumb-item active">Stallions Management / Edit Stallion</li>
	</ol>
	<div class="container">
		<%= form_for @stallion, :html => {:multipart => true} do |f| %>

			<% if @stallion.errors.any? %>
				<% @stallion.errors.full_messages.each do |msg| %>
					<div class="alert alert-danger"><%= msg %></div>
				<% end %>
			<% end %>
			
			<div class="form-row">
				<div class="form-group col-md-6">
					<%= f.label :name %>
					<%= f.text_field :name, class:'form-control '%>
				</div>
				<div class="form-group col-md-6">
					<%= f.label :birth_date %>
					<%= f.date_field :birth_date, class:'form-control '%>
				</div>
			</div>

			<div class="form-group">
				<div class="form-check">
					<%= f.label :for_sale %>
					<%= f.check_box :for_sale?, {class:'form-check-input'}, :checked=> false%>
				</div>
			</div>

			<div class="form-group">
				<%= f.label :price %>
				<%= f.number_field  :price, {class:'form-control col-md-2', placeholder:'Price($)'} %>
			</div>

			<div class="form-group">
				<%= f.label :image %>
				<div class="img-container">
					<%= image_tag @stallion.image.url, id:"img_prev1", class:"img-thumbnail hidden" %>
				</div>
				<%= f.file_field :image, id: "main-upload", :class => "btn btn-default", onchange:"preview_image(event, 'img_prev1')"%>
			</div>

			<div class="form-row">
				<div class="form-group col-md-6">
					<%= f.label :reg_number %>
					<%= f.text_field :reg_number, class:'form-control' %>
				</div>
				<div class="form-group col-md-3">
					<%= f.label :sex %>
					<%= f.text_field :sex, class:'form-control '%>
				</div>
				<div class="form-group col-md-3">
					<%= f.label :colour %>
					<%= f.text_field :colour, class:'form-control '%>
				</div>
			</div>

			<div class="form-row">
				<div class="form-group col-md-6">
					<%= f.label :markings %>
					<%= f.text_field :markings, class:'form-control '%>
				</div>

				<div class="form-group col-md-6">
					<%= f.label :breeder %>
					<%= f.text_field :breeder, class:'form-control '%>
				</div>
			</div>
			
			<div class="form-group">
				<%= f.label :description %>
				<%= f.text_area :description, class:'form-control', rows:'7'%>
			</div>

			<div class="form-group">
				<%= f.label :mother_name %>
				<%= f.text_field :mother_name, class:'form-control col-md-3'%>
			</div>

			<div class="form-group">
				<%= f.label :mother_image %>
				<div class="img-container">
					<%= image_tag @stallion.mother_image.url, id:"img_prev2", class:"img-thumbnail hidden" %>
				</div>
				<%= f.file_field :mother_image, id: "mother-upload", :class => "btn btn-default", onchange:"preview_image(event, 'img_prev2')"%>
			</div>

			<div class="form-group">
				<%= f.label :father_name %>
				<%= f.text_field :father_name, class:'form-control col-md-3' %>
			</div>

			<div class="form-group">
				<%= f.label :father_image %>
				<div class="img-container">
					<%= image_tag @stallion.father_image.url, id:"img_prev3", class:"img-thumbnail hidden" %>
				</div>
				<%= f.file_field :father_image, id: "father-upload", :class => "btn btn-default", onchange:"preview_image(event, 'img_prev3')"%>
			</div>

			<div class="form-group">
				<%= f.label :breeding_description %>
				<%= f.text_area :breeding_description, class:'form-control', rows:'7'%>
			</div>

			<%= f.submit "Submit", class:'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/stallions/new.html.erb
<div class="content">
	<ol class="breadcrumb">
		<li class="breadcrumb-item active">Stallions Management / Create Stallion</li>
	</ol>
	<div class="container">
		<%= form_for @stallion, :html => {:multipart => true} do |f| %>

			<% if @stallion.errors.any? %>
				<% @stallion.errors.full_messages.each do |msg| %>
					<div class="alert alert-danger"><%= msg %></div>
				<% end %>
			<% end %>

			<div class="form-row">
				<div class="form-group col-md-6">
					<%= f.label :name %>
					<%= f.text_field :name, class:'form-control', placeholder:'Name'%>
				</div>
				<div class="form-group col-md-6">
					<%= f.label :birth_date %>
					<%= f.date_field :birth_date, class:'form-control '%>
				</div>
			</div>

			<div class="form-group">
				<div class="form-check">
					<%= f.label :for_sale %>
					<%= f.check_box :for_sale?, {class:'form-check-input'}, :checked=> false%>
				</div>
			</div>


			<div class="form-group">
				<%= f.label :price %>
				<%= f.number_field  :price, {class:'form-control col-md-2', placeholder:'Price($)'} %>
			</div>


			<div class="form-group">
				<%= f.label :image %>
				<div class="img-container">
					<img id="img_prev1" src="#" alt="" class="img-thumbnail hidden"/>
				</div>
				<%= f.file_field :image, id: "main-upload", :class => "btn btn-default", onchange:"preview_image(event, 'img_prev1')"%>
			</div>

			<div class="form-row">
				<div class="form-group col-md-6">
					<%= f.label :reg_number %>
					<%= f.text_field :reg_number, class:'form-control', placeholder:'Rego Number' %>
				</div>
				<div class="form-group col-md-3">
					<%= f.label :sex %>
					<%= f.text_field :sex, class:'form-control', placeholder: 'Sex'%>
				</div>
				<div class="form-group col-md-3">
					<%= f.label :colour %>
					<%= f.text_field :colour, class:'form-control', placeholder:'Colour'%>
				</div>
			</div>

			<div class="form-row">
				<div class="form-group col-md-6">
					<%= f.label :markings %>
					<%= f.text_field :markings, class:'form-control', placeholder:'Markings'%>
				</div>

				<div class="form-group col-md-6">
					<%= f.label :breeder %>
					<%= f.text_field :breeder, class:'form-control', placeholder:'Breeder'%>
				</div>
			</div>

			<div class="form-group">
				<%= f.label :description %>
				<%= f.text_area :description, class:'form-control', rows:'7', placeholder:'Enter a description here ...'%>
			</div>

			<div class="form-group">
				<%= f.label :mother_name %>
				<%= f.text_field :mother_name, class:'form-control col-md-3', placeholder:'Mothers Name'%>
			</div>

			<div class="form-group">
				<%= f.label :mother_image %>
				<div class="img-container">
					<img id="img_prev2" src="#" alt="" class="img-thumbnail hidden"/>
				</div>
				<%= f.file_field :mother_image, id: "mother-upload", :class => "btn btn-default", onchange:"preview_image(event, 'img_prev2')"%>
			</div>

			<div class="form-group">
				<%= f.label :father_name %>
				<%= f.text_field :father_name, class:'form-control col-md-3', placeholder:'Fathers Name' %>
			</div>

			<div class="form-group">
				<%= f.label :father_image %>
				<div class="img-container">
					<img id="img_prev3" src="#" alt="" class="img-thumbnail hidden"/>
				</div>
				<%= f.file_field :father_image, id: "father-upload", :class => "btn btn-default", onchange:"preview_image(event, 'img_prev3')"%>
			</div>

			<div class="form-group">
				<%= f.label :breeding_description %>
				<%= f.text_area :breeding_description, class:'form-control', rows:'7', placeholder:'Enter description about breeding history here ...'%>
			</div>

			<%= f.submit "Submit", class:'btn btn-primary' %>
		<% end %>
	</div>
</div>